stages:
  - build
  - test
  - dockerbuild
  - deploy
  
test:
  stage: test
  image: gradle:jdk15
  tags:
    - k8s-executor
  script: gradle check --info

dockerbuild:
  stage: dockerbuild
  tags:
    - k8s-executor
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
      when: on_success
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:latest

deploy:
  stage: deploy
  tags:
    - k8s
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
      when: on_success
  variables:
    GIT_STRATEGY: none
  before_script:
    - kubectl --kubeconfig="$KUBE_CONFIG_FILE" describe deployment/kotbot
  script:
    - kubectl --kubeconfig="$KUBE_CONFIG_FILE" rollout restart deployment/kotbot
