apiVersion: apps/v1
kind: Deployment
metadata:
  name: kotbot
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: kotbot
  replicas: 1
  template:
    metadata:
      labels:
        app: kotbot
    spec:
      volumes:
        - name: kotbot-persistent-storage
          persistentVolumeClaim:
            claimName: kotbot-pv-claim
      containers:
        - name: kotbot-bot
          image: registry.gitlab.com/update-gitlab.yml/kotlinspringbot:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 1
              memory: 1Gi
      containers:
        - name: kotbot-db
          image: mongo:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 1
              memory: 512Mi
          volumeMounts:
            - mountPath: /data/db
              name: kotbot-persistent-storage

