version: "3.8"

services:
  db:
    image: mongo
    volumes:
     - type: volume
       source: data
       target: /data/db
    ports:
      - '27017:27017'
  bot:
    image: registry.gitlab.com/update-gitlab.yml/kotlinspringbot:latest
    configs:
      - source: kotlin-bot-config-v2
        target: /application.properties
    depends_on:
      - db

configs:
  kotlin-bot-config-v2:
    external: true
volumes:
  data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.40,nolock,soft,rw
      device: ":/nfs/docker/kotlinBotMongo"

